apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp2-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp2-k8s
    spec:
      containers:
      - image: asia.gcr.io/test-webapp2-143703/test-webapp2:20160917-1127
        name: webapp2-k8s
        ports:
          - containerPort: 8080
